### ISSUE TITLE
Migrate to SOPS for repo

### ISSUE THREAD

**Issue by wrmilling** [wrmilling/k3s-gitops#144]
Looking at migrating to SOPS (Seems to be in-vogue). 

- [ ] Update secrets generations scripts
- [ ] Migrate existing secret templates to main Helm Charts where possible
- [ ] Migrate non-helm chart secrets to their own yaml? 
- [ ] Get rid of .env for this? 
- [ ] Storage of secret keys for encryption/decryption? 
- [ ] How to handle restart of containers where secrets have been updated? 

More thoughts to come.

**Comment by tuxpeople** [comment]
Hi Winston

Came across your repo while searching for inspiration for my own gitops repo and stumbled over this issue. I'm wondering what reasons you have to migrate, aside from SOPS beeing more popular in the homelab-k3s-gitops-bubble here on Github. Which is something I also noticed. I myself using Sealed Secrets as well and I'm keen to learn what SOPS is doing better.

Br
Thomas

**Comment by wrmilling** [comment]
Hey @tuxpeople, 

Honestly, I have not much trouble with sealed-secrets (which is why this was written in May and not yet acted on) and could potentially keep going with my current solution. But, I know that by moving to a SOPS-based workflow I can get rid of multiple tools (git-crypt and sealed-secrets) for a single tool that can handle secrets for the cluster in a highly supported way via Flux v2. It will integrate well with my [yubikey usage](https://github.com/drduh/YubiKey-Guide), be [fairly seamless](https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops) (similar to git-crypt by itself) in my workflow, and overall should reduce the number of files I have to maintain in the repo. 

I draw a bit of inspiration for a SOPS setup from the [k8s-at-home template cluster](https://github.com/k8s-at-home/template-cluster-k3s) and will probably be following it loosely when I do migrate. 

Thanks for reminding me I wrote this up, might be time to test SOPS out fully. 

Regards, 

Winston

**Comment by wrmilling** [comment]
Started migration to SOPS today, moving namespace by namespace to move secrets to SOPS.

**Comment by wrmilling** [comment]
SOPS migration complete, maintained a sops-encryption.sh script which performed the initial encryption of the new files, but otherwise will only be maintaining the template files and original .env as a best effort endeavor.
