### ISSUE TITLE
Try out Blocky as piHole Replacement

### ISSUE THREAD

**Issue by wrmilling** [wrmilling/k3s-gitops#165]
- [ ] Investigate Deploying Blocky
- [ ] Translate custom DNS entries over to blocky
- [ ] Investigate getting the nodeAffinity to deploy a single instance to each half of my cluster (if possible)
- [ ] Migrate all existing DNS to new IP addresses (if required)
- [ ] Validate node DNS servers

**Comment by samip5** [comment]
Please link Blocky?

**Comment by wrmilling** [comment]
Hello @samip5, I have not done the investigation of using it on my own cluster yet, but take a look at the links below: 

- [Blocky Main Repo](https://github.com/0xERR0R/blocky)
- [k8s-at-home Blocky Helm Chart](https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky)
- [Example Fluxv2 HelmRelease](https://github.com/billimek/k8s-gitops/blob/master/default/blocky/blocky.yaml) using above chart

**Comment by wrmilling** [comment]
I have piHole running in a stateless and fairly high availability manner at this point with pod topology spread constraints and metallb electing and announcing the right node, I am going to shelve this issue for the time being and re-visit if I run into trouble with my [current setup](https://github.com/wrmilling/k3s-gitops/blob/master/default/pihole/).
